# Generated by Django 5.2 on 2026-01-19 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ai_assistant', '0008_category_article_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='django_ai_assistant.agent'),
        ),
        migrations.AddField(
            model_name='category',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='django_ai_assistant.agent'),
        ),
        migrations.AddField(
            model_name='faq',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='django_ai_assistant.agent'),
        ),
    ]
