# Generated by Django 5.2 on 2026-01-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ai_assistant', '0010_articletype_language_tag_remove_article_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
