# Generated by Django 5.2 on 2026-01-19 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ai_assistant', '0012_customeruser_thread_customer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='django_user',
            field=models.ForeignKey(blank=True, help_text='Associated Django user for authentication/internal use.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
