# Generated by Django 5.2 on 2026-01-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ai_assistant', '0013_customeruser_django_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='channel',
            field=models.CharField(choices=[('live_chat', 'Live Chat'), ('whatsapp', 'WhatsApp')], default='live_chat', help_text='The channel through which this conversation is happening.', max_length=50),
        ),
    ]
