# Generated by Django 5.2 on 2026-01-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ai_assistant', '0014_thread_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='channel',
            field=models.CharField(choices=[('live_chat', 'Live Chat'), ('whatsapp', 'WhatsApp'), ('ai_agent', 'Agent Chat')], default='live_chat', help_text='The channel through which this conversation is happening.', max_length=50),
        ),
    ]
