# Generated by Django 5.2 on 2026-01-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ai_assistant', '0016_thread_is_human_handoff_alter_thread_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('ai', 'AI Assistant'), ('customer', 'Customer'), ('support', 'Support Staff'), ('anonymous', 'Anonymous User')], default='ai', help_text='Type of sender: AI, customer, support staff, or anonymous user.', max_length=20),
        ),
    ]
